4.2.4

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -5026,13 +5026,14 @@ done
 
 
 
+
 for ac_header in sys/time.h sys/times.h sys/select.h termcap.h termio.h \
 		 termios.h sys/param.h sys/filio.h string.h memory.h \
 		 limits.h fcntl.h libc.h sys/utsname.h sys/resource.h \
 		 locale.h errno.h stdio.h stdlib.h unistd.h sys/capability.h \
 		 utmp.h utmpx.h sys/types.h pwd.h grp.h poll.h sys/mman.h \
 		 netinet/in_systm.h pcre.h langinfo.h wchar.h stddef.h \
-		 sys/stropts.h
+		 sys/stropts.h iconv.h
 do
 as_ac_Header=`echo "ac_cv_header_$ac_header" | $as_tr_sh`
 if eval "test \"\${$as_ac_Header+set}\" = set"; then
@@ -7584,14 +7585,15 @@ _ACEOF
 fi
 
 
-if test x$enable_pcre = xyes; then
-echo "$as_me:$LINENO: checking for library containing pcre_compile" >&5
-echo $ECHO_N "checking for library containing pcre_compile... $ECHO_C" >&6
-if test "${ac_cv_search_pcre_compile+set}" = set; then
+if test "$host_os" = cygwin; then
+
+echo "$as_me:$LINENO: checking for libiconv in -liconv" >&5
+echo $ECHO_N "checking for libiconv in -liconv... $ECHO_C" >&6
+if test "${ac_cv_lib_iconv_libiconv+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
 else
-  ac_func_search_save_LIBS=$LIBS
-ac_cv_search_pcre_compile=no
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-liconv  $LIBS"
 cat >conftest.$ac_ext <<_ACEOF
 /* confdefs.h.  */
 _ACEOF
@@ -7605,11 +7607,11 @@ extern "C"
 #endif
 /* We use char because int might match the return type of a gcc2
    builtin and then its argument prototype would still apply.  */
-char pcre_compile ();
+char libiconv ();
 int
 main ()
 {
-pcre_compile ();
+libiconv ();
   ;
   return 0;
 }
@@ -7636,81 +7638,32 @@ if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
   ac_status=$?
   echo "$as_me:$LINENO: \$? = $ac_status" >&5
   (exit $ac_status); }; }; then
-  ac_cv_search_pcre_compile="none required"
+  ac_cv_lib_iconv_libiconv=yes
 else
   echo "$as_me: failed program was:" >&5
 sed 's/^/| /' conftest.$ac_ext >&5
 
+ac_cv_lib_iconv_libiconv=no
 fi
 rm -f conftest.err conftest.$ac_objext \
       conftest$ac_exeext conftest.$ac_ext
-if test "$ac_cv_search_pcre_compile" = no; then
-  for ac_lib in pcre; do
-    LIBS="-l$ac_lib  $ac_func_search_save_LIBS"
-    cat >conftest.$ac_ext <<_ACEOF
-/* confdefs.h.  */
+LIBS=$ac_check_lib_save_LIBS
+fi
+echo "$as_me:$LINENO: result: $ac_cv_lib_iconv_libiconv" >&5
+echo "${ECHO_T}$ac_cv_lib_iconv_libiconv" >&6
+if test $ac_cv_lib_iconv_libiconv = yes; then
+  cat >>confdefs.h <<_ACEOF
+#define HAVE_LIBICONV 1
 _ACEOF
-cat confdefs.h >>conftest.$ac_ext
-cat >>conftest.$ac_ext <<_ACEOF
-/* end confdefs.h.  */
 
-/* Override any gcc2 internal prototype to avoid an error.  */
-#ifdef __cplusplus
-extern "C"
-#endif
-/* We use char because int might match the return type of a gcc2
-   builtin and then its argument prototype would still apply.  */
-char pcre_compile ();
-int
-main ()
-{
-pcre_compile ();
-  ;
-  return 0;
-}
-_ACEOF
-rm -f conftest.$ac_objext conftest$ac_exeext
-if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
-  (eval $ac_link) 2>conftest.er1
-  ac_status=$?
-  grep -v '^ *+' conftest.er1 >conftest.err
-  rm -f conftest.er1
-  cat conftest.err >&5
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); } &&
-	 { ac_try='test -z "$ac_c_werror_flag"
-			 || test ! -s conftest.err'
-  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
-  (eval $ac_try) 2>&5
-  ac_status=$?
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); }; } &&
-	 { ac_try='test -s conftest$ac_exeext'
-  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
-  (eval $ac_try) 2>&5
-  ac_status=$?
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); }; }; then
-  ac_cv_search_pcre_compile="-l$ac_lib"
-break
-else
-  echo "$as_me: failed program was:" >&5
-sed 's/^/| /' conftest.$ac_ext >&5
-
-fi
-rm -f conftest.err conftest.$ac_objext \
-      conftest$ac_exeext conftest.$ac_ext
-  done
-fi
-LIBS=$ac_func_search_save_LIBS
-fi
-echo "$as_me:$LINENO: result: $ac_cv_search_pcre_compile" >&5
-echo "${ECHO_T}$ac_cv_search_pcre_compile" >&6
-if test "$ac_cv_search_pcre_compile" != no; then
-  test "$ac_cv_search_pcre_compile" = "none required" || LIBS="$ac_cv_search_pcre_compile $LIBS"
+  LIBS="-liconv $LIBS"
 
 fi
 
+fi
+
+if test x$enable_pcre = xyes; then
+  LIBS="`pcre-config --libs` $LIBS"
 fi
 
 echo "$as_me:$LINENO: checking if an include file defines ospeed" >&5
@@ -12255,6 +12208,140 @@ _ACEOF
 fi
 
 
+echo "$as_me:$LINENO: checking for limit RLIMIT_SIGPENDING" >&5
+echo $ECHO_N "checking for limit RLIMIT_SIGPENDING... $ECHO_C" >&6
+if test "${zsh_cv_have_RLIMIT_SIGPENDING+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+#include <sys/types.h>
+#ifdef HAVE_SYS_TIME_H
+#include <sys/time.h>
+#endif
+#include <sys/resource.h>
+int
+main ()
+{
+RLIMIT_SIGPENDING
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  zsh_cv_have_RLIMIT_SIGPENDING=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+zsh_cv_have_RLIMIT_SIGPENDING=no
+fi
+rm -f conftest.err conftest.$ac_objext conftest.$ac_ext
+fi
+echo "$as_me:$LINENO: result: $zsh_cv_have_RLIMIT_SIGPENDING" >&5
+echo "${ECHO_T}$zsh_cv_have_RLIMIT_SIGPENDING" >&6
+
+if test $zsh_cv_have_RLIMIT_SIGPENDING = yes; then
+  cat >>confdefs.h <<\_ACEOF
+#define HAVE_RLIMIT_SIGPENDING 1
+_ACEOF
+
+fi
+
+
+echo "$as_me:$LINENO: checking for limit RLIMIT_MSGQUEUE" >&5
+echo $ECHO_N "checking for limit RLIMIT_MSGQUEUE... $ECHO_C" >&6
+if test "${zsh_cv_have_RLIMIT_MSGQUEUE+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+#include <sys/types.h>
+#ifdef HAVE_SYS_TIME_H
+#include <sys/time.h>
+#endif
+#include <sys/resource.h>
+int
+main ()
+{
+RLIMIT_MSGQUEUE
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  zsh_cv_have_RLIMIT_MSGQUEUE=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+zsh_cv_have_RLIMIT_MSGQUEUE=no
+fi
+rm -f conftest.err conftest.$ac_objext conftest.$ac_ext
+fi
+echo "$as_me:$LINENO: result: $zsh_cv_have_RLIMIT_MSGQUEUE" >&5
+echo "${ECHO_T}$zsh_cv_have_RLIMIT_MSGQUEUE" >&6
+
+if test $zsh_cv_have_RLIMIT_MSGQUEUE = yes; then
+  cat >>confdefs.h <<\_ACEOF
+#define HAVE_RLIMIT_MSGQUEUE 1
+_ACEOF
+
+fi
+
+
 
 echo "$as_me:$LINENO: checking if RLIMIT_VMEM and RLIMIT_RSS are the same" >&5
 echo $ECHO_N "checking if RLIMIT_VMEM and RLIMIT_RSS are the same... $ECHO_C" >&6
@@ -14588,7 +14675,10 @@ echo $ECHO_N "checking if named FIFOs work... $ECHO_C" >&6
 if test "${zsh_cv_sys_fifo+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
 else
-  if test "$cross_compiling" = yes; then
+  if test "$host_os" = cygwin; then
+zsh_cv_sys_fifo=no
+else
+if test "$cross_compiling" = yes; then
   zsh_cv_sys_fifo=yes
 else
   cat >conftest.$ac_ext <<_ACEOF
@@ -14647,6 +14737,7 @@ sed 's/^/| /' conftest.$ac_ext >&5
 zsh_cv_sys_fifo=no
 fi
 rm -f core *.core gmon.out bb.out conftest$ac_exeext conftest.$ac_objext conftest.$ac_ext
+fi
 fi
 fi
 echo "$as_me:$LINENO: result: $zsh_cv_sys_fifo" >&5
